### ISSUE TITLE
Samsung Internet

### ISSUE THREAD

**Issue by KseniaZhe** [SridharShrinidhi/shrinidhisridhar-portfolio#14]
![47580412_2199578720358947_7815494719437275136_n](https://user-images.githubusercontent.com/22149553/49895148-be98ed00-fe1d-11e8-9b44-5bab76097844.png)
![48259040_2417942278247440_1735329249016938496_n](https://user-images.githubusercontent.com/22149553/49895150-bf318380-fe1d-11e8-91ab-28186bf1b080.png)

**Comment by KseniaZhe** [comment]
it is only weird when there is a browser bar at the bottom

**Comment by SridharShrinidhi** [comment]
Thanks Ksenia, the spacing issue was resolved
