### ISSUE TITLE
Android, Opera Mini, In-class testing

### ISSUE THREAD

**Issue by elbe0011** [SridharShrinidhi/shrinidhisridhar-portfolio#15]
Some text gets cut off on small screen sizes. See picture: 
![screenshot_20181212-145104_chrome](https://user-images.githubusercontent.com/22224735/49895282-0d468700-fe1e-11e8-9008-aee7d9b7f357.jpg)

**Comment by SridharShrinidhi** [comment]
Resolved using word break
