### ISSUE TITLE
Safari testing

### ISSUE THREAD

**Issue by fakeha-abdullah** [SridharShrinidhi/shrinidhisridhar-portfolio#17]
- Website is unique with the slide scrolling and although I was a bit confused at the beginning, it makes sense once the user gets the hang of it. Website, is nicely responsive and content is short and to the point. 
- Images are not high quality.
- I love the little nav at the bottom of the page and the links to detailed pages.

Overall, Well done my friend you're a web design freak :P !

**Comment by SridharShrinidhi** [comment]
Ha ha, thanks FA! :D Will take a look at the images.
