### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by krystyna-Macleod** [SridharShrinidhi/shrinidhisridhar-portfolio#9]
The issue I see on iPhone 7 Safari is the spacing on the Influenza app page that it looks like it's on top of the header.

Everything else looks amazing!
![img_0052](https://user-images.githubusercontent.com/22229572/49894645-73320f00-fe1c-11e8-9fbb-696a3def1940.jpg)

**Comment by SridharShrinidhi** [comment]
Thanks Krystyna! Will check it out.
